### PR TITLE
Feat: how it works section & adjusted get in touch section

### LINKED ISSUE #5: Create How It Works
image

- [ ] Desktop

- [ ] Mobile

### LINKED ISSUE #6: Create Get In Touch
image

- [ ] Desktop

- [ ] Mobile

### PR DESCRIPTION
**Pull request by andrerebonato**
It was finished how it works section and adjusted the get in touch section too.

How it works:
how-it-works
how-it-works-en

fixed-how-it-works

It was changed the get in touch section too, a picture of the section before the changes:
getInTouch-before

After changes:
fixed

### CODE REVIEW

**Comment by vitorregisrr** [comment]
Hey Andre!

Nice  to see that, thank you so much.

I really like the structure of your code.

There is just some styling things we can improve to make it look more the template:

- The letter-spacing of the How It Works title is different from the layout

image

image

- May can we add an container in that?
image
image

- May can we decrease the title size in mobile and center that?
image

- Decrease that font size in mobile too (and can also add a bigger padding in the top and in the bottom of the last list item)
image

- Review the height of the inputs in Get in Touch 
image


I think is that! Thank you!

**Review by vitorregisrr — CHANGES_REQUESTED** [review]
The requested changes is above.

**Comment by andrerebonato** [comment]
> The requested changes is above.

Done, please, check again.

**Comment by vitorregisrr** [comment]
Nice! thank you

**Review by vitorregisrr — APPROVED** [review]

**Pull request merged**
